from .cities_pipeline import get_cities_pipeline
from .common_master_pipeline import load_common_master_tables
from .ltc_analysis_pipeline import get_ltc_analysis_pipeline
from .medical_analysis_pipeline import get_medical_analysis_pipeline
from .population_change_detail_pipeline import get_population_change_detail_pipeline
from .population_composition_pipeline import get_population_composition_pipeline
from .population_future_pipeline import get_population_future_pipeline
from .population_pyramid_pipeline import get_population_pyramid_pipeline
from .population_society_pipeline import get_population_society_pipeline
# add other jobs here
