[destination.bigquery]
location = "asia-northeast1"
dataset_name = "dl_localgov_kpi_database"
# dataset_name = "resas_api_data"


[runtime]
log_level = "INFO" # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/telemetry
dlthub_telemetry = false
